spin_manifest_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Spin Python SDK sqlite example"
name = "spin-py-sqlite"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "python-sdk-example"
source = "app.wasm"
sqlite_databases = ["default"]
[component.trigger]
route = "/..."
[component.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py"]
